.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, src/main/resources/swagger.api/mgr-tenants.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
=> FOLIO-3678 FOLIO-3938 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml
Upgrade Keycloak client to the latest - `v23.0.3`
- Upgrade Keycloak client to the latest - `v23.0.3` by upgrading dependencies:
- `folio-backend-testing`
- `folio-security`
environment. Communication is paramount if that is …
=> MGRTENANT-8 Upgrade Keycloak client to v23.0.3

pom.xml, src/main/java/org/folio/tm/domain/entity/TenantEntity.java
The official version of Spring for Quesnelia is 3.2 (see https://wiki.folio.org/display/TC/Quesnelia).
- Upgrade Spring Boot parent version and affected libraries, plugins
environment. Communication is paramount if that is …
=> MODROLESKC-21 Upgrade Spring Boot to v3.2.1

.github/CODEOWNERS, .gitignore, PERSONAL_DATA_DISCLOSURE.md, pom.xml
Maven deploy works not properly. It should be fixed.
- fix pom file
- add required files
inter-team dependencies …
=> FIX: maven deploy

Jenkinsfile, src/test/java/org/folio/tm/extension/impl/PostgresContainerExtension.java
Fix build issues with insufficient resources by changing Jenkins build node to "bigmem", updating postgres image to "alpine" version to decrease image size
environment. Communication is paramount if that is to be achieved, …
=> Change Jenkins build node to "bigmem", use postgres "alpine" image for test containers

pom.xml
Raises version of `folio-security` to `v1.3.0-SNAPSHOT`
- Raise version of `folio-security` to `1.3.0-SNAPSHOT`
- Raise version of `folio-backend-testing` to `1.3.0-SNAPSHOT` 
environment. Communication is paramount if that …
=> KEYCLOAK-6 Raise version of 'folio-security' to v1.3.0-SNAPSHOT

pom.xml
Raise applications-poc-tools to v1.3.0-SNAPSHOT
inter-team dependencies increase.
While it's helpful for …
=> MGRAPPS-8 Raise applications-poc-tools to v1.3.0-SNAPSHOT

NEWS.md, pom.xml
Releases v1.1.0 and prepares `1.2.0-SNAPSHOT` for further development
- Add and update NEWS.md
inter-team …
=> MGRENTITLE-16 Release v1.1.0

src/test/java/org/folio/tm/it/TenantKeycloakIT.java
Braking changes were added in application-poc-tools. Keycloak-related tests should be updated.
- update tests …
=> Update Keycloak-related tests

README.md, pom.xml, src/main/java/org/folio/tm/integration/keycloak/configuration/KeycloakConfiguration.java, src/main/resources/application.yml, src/test/resources/application-it.yml
Keycloak client: add support TLS certificates issued by trusted certificate authorities
inter-team dependencies …
=> MGRTENANT-26: Keycloak client: add support TLS certificates issued by trusted certificate authorities

Jenkinsfile
Relate Jira Ticket:
[RANCHER-1515: prepare & merge PRs for RANCHER-1502 part1](https://folio-org.atlassian.net/browse/RANCHER-1515)
=> RANCHER-1515: put application to Docker Image and upload to ECR

src/test/java/org/folio/tm/extension/impl/KongGatewayExtension.java
Upgrade kong version to 3.7.1
inter-team dependencies increase.
While it's helpful for reviewers to help …
=> KONG-10: upgrade kong version to 3.7.1

pom.xml, src/main/java/org/folio/tm/integration/keycloak/KeycloakRealmService.java, src/main/java/org/folio/tm/integration/keycloak/configuration/KeycloakConfiguration.java, src/main/java/org/folio/tm/integration/keycloak/model/Realm.java, src/main/resources/json/realms/authentication-required-actions.json, src/main/resources/json/realms/user-profile-configuration.json, src/test/java/org/folio/tm/service/KeycloakRealmServiceTest.java, src/test/java/org/folio/tm/support/TestConstants.java
Upgrade keycloak client to `v25.0.1`
- Use `applicaiton-poc-tools` `v1.5.3-SNAPSHOT` with latest keycloak client
- Add default user profile settings to disable validation for usernames
environment. Communication is paramount …
=> MGRTENANT-28 Upgrade keycloak client to v25.0.1

NEWS.md, pom.xml
=> Release 1.3.3

Dockerfile, pom.xml, src/main/resources/application.yml, src/test/java/org/folio/tm/base/BaseIntegrationTest.java, src/test/java/org/folio/tm/controller/TenantControllerTest.java, src/test/java/org/folio/tm/it/TenantOkapiIT.java, src/test/java/org/folio/tm/support/TestUtils.java, src/test/resources/wiremock/stubs/mod-authtoken/verify-token-create-tenant.json, src/test/resources/wiremock/stubs/mod-authtoken/verify-token-delete-tenant.json, src/test/resources/wiremock/stubs/mod-authtoken/verify-token-update-not-authorized.json, src/test/resources/wiremock/stubs/mod-authtoken/verify-token-update-permission-denied.json, src/test/resources/wiremock/stubs/mod-authtoken/verify-token-update-tenant.json, src/test/resources/wiremock/stubs/okapi/create-tenant.json, src/test/resources/wiremock/stubs/okapi/delete-tenant.json, src/test/resources/wiremock/stubs/okapi/get-tenant-exist.json, src/test/resources/wiremock/stubs/okapi/get-tenant-not-found.json, src/test/resources/wiremock/stubs/okapi/update-tenant.json
Injects and uses a common library for an authentication process.
- Use `folio-auth-openid` as a dependency for JWT verification
- Adjust unit and integration tests
environment. Communication is paramount if that is to be …
=> APPPOCTOOL-28 Use folio-auth-openid library for JWT validation

src/main/java/org/folio/tm/integration/keycloak/service/clients/LoginClientService.java, src/test/java/org/folio/tm/integration/keycloak/service/clients/LoginClientServiceTest.java
Fixes invalid policy name after code refactoring
- Fix invalid policy name after code refactoring
- Adjust related unit test
environment. Communication is paramount if that is to be achieved, especially as the number of …
=> MGRTENANT-34 Fix password reset policy name

src/main/java/org/folio/tm/integration/keycloak/KeycloakRealmService.java, src/main/java/org/folio/tm/integration/keycloak/configuration/KeycloakConfiguration.java, src/main/java/org/folio/tm/integration/keycloak/configuration/KeycloakRealmSetupProperties.java, src/main/resources/application.yml, src/test/java/org/folio/tm/integration/keycloak/KeycloakRealmServiceTest.java
For new tenants creation during tenant entitlement process we are getting timeout error
[MGRTENANT-47](https://folio-org.atlassian.net/browse/MGRTENANT-47)
- Set up  a higher timeouts inside Keycloak for newly created realms …
=> MGRTENANT-47: Entitlement issue for newly created tenant due to default keycloak configurations

Dockerfile, Jenkinsfile, docker/Dockerfile.fips, pom.xml
https://folio-org.atlassian.net/browse/MGRTENANT-49
Upgrade Java to version 21
inter-team dependencies increase. …
=> MGRTENANT-49: Upgrade Java to version 21.

checkstyle/checkstyle-checker.properties, checkstyle/checkstyle-suppressions.xml, pom.xml, src/main/java/org/folio/tm/integration/kafka/KafkaService.java, src/main/java/org/folio/tm/integration/keycloak/KeycloakRealmService.java, src/main/java/org/folio/tm/integration/keycloak/service/clients/AbstractKeycloakClientService.java, src/main/java/org/folio/tm/integration/keycloak/service/clients/ImpersonationClientService.java
Add method length checkstyle rule and refactor code for compliance
---
=> feat(checkstyle): add method length checkstyle rule and refactor code for compliance

src/main/resources/application.yml
[MGRTENANT-64](https://folio-org.atlassian.net/browse/MGRTENANT-64) - Use SECURE_STORE_ENV, not ENV, for secure store key
Provide a brief technical summary of the changes.
---
=> MGRTENANT-64 - SECURE_STORE_ENV use ENV value if exist
